
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;
import java.sql.*;
import java.net.*;

public class LoginOrRegisterForm extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement statement = null;
    ResultSet result = null;
    
    public boolean isAdmin = true;
    boolean isShown = true;
    
    public LoginOrRegisterForm() {
        initComponents();
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/grampis", "root", "");
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
        setLocationRelativeTo(null);
        jpfPassword.setEchoChar('*');
        
        displayIcon();
        setIcon();
    }
    
    class jPanelGradient extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int w = getWidth();
            int h = getHeight();
            
            Color color1 = new Color(0,176,178);
            Color color2 = new Color(159,193,211);
            GradientPaint gp = new GradientPaint(0,0,color1,0,h,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,w,h);
        }
    }
    
    class JButtonWithRadius extends JButton {
        private int radius;
        private Color hoverBackgroundColor;
        private Color originalBackgroundColor;

        public JButtonWithRadius(String text, int radius, Color hoverBackgroundColor) {
            super(text);
            this.radius = radius;
            this.originalBackgroundColor = getBackground();
            this.hoverBackgroundColor = hoverBackgroundColor;

            // Add mouse listener to change the background color on hover
            addMouseListener(new MouseAdapter() {
                public void mouseEntered(MouseEvent e) {
                    originalBackgroundColor = getBackground();
                    setBackground(hoverBackgroundColor);
                }

                public void mouseExited(MouseEvent e) {
                    setBackground(originalBackgroundColor);
                }
            });
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g.create();

            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            g2d.setColor(getBackground());
            g2d.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);

            g2d.setColor(getForeground());
            FontMetrics fm = g2d.getFontMetrics();
            int x = (getWidth() - fm.stringWidth(getText())) / 2;
            int y = (getHeight() + fm.getHeight()) / 2;
            g2d.drawString(getText(), x, y);

            g2d.dispose();
        }

        @Override
        public Dimension getPreferredSize() {
            Dimension size = super.getPreferredSize();
            size.width += radius;
            size.height += radius;
            return size;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient();
        jlNeustLogo = new javax.swing.JLabel();
        jlCictLogo = new javax.swing.JLabel();
        jlGramLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtpLoginOrRegister = new javax.swing.JTabbedPane();
        jpLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlShowOrHide = new javax.swing.JLabel();
        jlUserIcon = new javax.swing.JLabel();
        btnLogin = new JButtonWithRadius("LOGIN", 25, new Color(36, 59, 85));
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jlCreateAccount = new javax.swing.JLabel();
        jlLockIcon = new javax.swing.JLabel();
        jpRegister = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlLockIcon1 = new javax.swing.JLabel();
        jlUserIcon1 = new javax.swing.JLabel();
        jtfUsername1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jpfPassword1 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        btnRegister = new JButtonWithRadius("REGISTER", 25, new Color(36, 59, 85));
        jlShowOrHide1 = new javax.swing.JLabel();
        btnCancel = new JButtonWithRadius("Cancel", 25, new Color(36, 59, 85));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Inventory System");
        setPreferredSize(new java.awt.Dimension(750, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(63, 100, 126));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 450));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Inventory System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlNeustLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlCictLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jlGramLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNeustLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCictLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlGramLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        jpLogin.setBackground(new java.awt.Color(0, 176, 178));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign In");

        jtfUsername.setBackground(new java.awt.Color(0, 176, 178));
        jtfUsername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jtfUsername.setForeground(new java.awt.Color(255, 255, 255));
        jtfUsername.setToolTipText("Enter username");
        jtfUsername.setBorder(null);
        jtfUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jpfPassword.setBackground(new java.awt.Color(0, 176, 178));
        jpfPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jpfPassword.setForeground(new java.awt.Color(255, 255, 255));
        jpfPassword.setToolTipText("Enter password");
        jpfPassword.setBorder(null);
        jpfPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jlShowOrHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myImg/lockIcon.png"))); // NOI18N
        jlShowOrHide.setToolTipText("Show Password");
        jlShowOrHide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlShowOrHide.setName(""); // NOI18N
        jlShowOrHide.setPreferredSize(new java.awt.Dimension(30, 30));
        jlShowOrHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlShowOrHideMouseClicked(evt);
            }
        });

        jlUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myImg/userIcon.png"))); // NOI18N
        jlUserIcon.setName(""); // NOI18N
        jlUserIcon.setPreferredSize(new java.awt.Dimension(30, 30));

        btnLogin.setBackground(new java.awt.Color(63, 100, 126));
        btnLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Don't have an account?");

        jlCreateAccount.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jlCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        jlCreateAccount.setText("Create one");
        jlCreateAccount.setToolTipText("Create new account");
        jlCreateAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCreateAccountMouseClicked(evt);
            }
        });

        jlLockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myImg/lockIcon.png"))); // NOI18N
        jlLockIcon.setName(""); // NOI18N
        jlLockIcon.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
        jpLogin.setLayout(jpLoginLayout);
        jpLoginLayout.setHorizontalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpLoginLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlCreateAccount))
                        .addGroup(jpLoginLayout.createSequentialGroup()
                            .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlLockIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfUsername)
                                    .addComponent(jpfPassword)
                                    .addComponent(jSeparator1)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlShowOrHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpLoginLayout.setVerticalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlShowOrHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLockIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlCreateAccount))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jtpLoginOrRegister.addTab("tab1", jpLogin);

        jpRegister.setBackground(new java.awt.Color(159, 193, 211));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign Up");

        jlLockIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myImg/lockIcon.png"))); // NOI18N
        jlLockIcon1.setName(""); // NOI18N
        jlLockIcon1.setPreferredSize(new java.awt.Dimension(30, 30));

        jlUserIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myImg/userIcon.png"))); // NOI18N
        jlUserIcon1.setName(""); // NOI18N
        jlUserIcon1.setPreferredSize(new java.awt.Dimension(30, 30));

        jtfUsername1.setBackground(new java.awt.Color(159, 193, 211));
        jtfUsername1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jtfUsername1.setForeground(new java.awt.Color(255, 255, 255));
        jtfUsername1.setToolTipText("Enter username");
        jtfUsername1.setBorder(null);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jpfPassword1.setBackground(new java.awt.Color(159, 193, 211));
        jpfPassword1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jpfPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jpfPassword1.setToolTipText("Enter password");
        jpfPassword1.setBorder(null);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        btnRegister.setBackground(new java.awt.Color(63, 100, 126));
        btnRegister.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setBorder(null);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jlShowOrHide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myImg/lockIcon.png"))); // NOI18N
        jlShowOrHide1.setToolTipText("Show Password");
        jlShowOrHide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlShowOrHide1.setName(""); // NOI18N
        jlShowOrHide1.setPreferredSize(new java.awt.Dimension(30, 30));
        jlShowOrHide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlShowOrHide1MouseClicked(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(63, 100, 126));
        btnCancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("cancel");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRegisterLayout = new javax.swing.GroupLayout(jpRegister);
        jpRegister.setLayout(jpRegisterLayout);
        jpRegisterLayout.setHorizontalGroup(
            jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jpRegisterLayout.createSequentialGroup()
                        .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLockIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlUserIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfUsername1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jpfPassword1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRegisterLayout.createSequentialGroup()
                                .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlShowOrHide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpRegisterLayout.setVerticalGroup(
            jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUserIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLockIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlShowOrHide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jtpLoginOrRegister.addTab("tab2", jpRegister);

        getContentPane().add(jtpLoginOrRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, -34, 410, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCreateAccountMouseClicked
        // TODO add your handling code here:
        jtpLoginOrRegister.setSelectedIndex(1);
    }//GEN-LAST:event_jlCreateAccountMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String username, password, role = "User";
        username = jtfUsername1.getText();
        password = jpfPassword1.getText();
        
        if(username.equals("") && password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your username and password.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(username.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your username.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your password.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try{
                String query = "INSERT INTO `tbluser`(`username`, `password`, `role`) VALUES ('"+username+"','"+password+"','"+role+"')";
                statement = con.prepareStatement(query);
                statement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Insert operation successful.", "Success", JOptionPane.INFORMATION_MESSAGE);

                jtfUsername1.setText("");
                jpfPassword1.setText("");
                jtpLoginOrRegister.setSelectedIndex(0);

            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        MainForm toMainForm = new MainForm();
        String username, password, role = "";
        
        username = jtfUsername.getText();
        password = jpfPassword.getText();
        
        if(username.equals("") && password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your username and password.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(username.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your username.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your password.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sql = "SELECT * FROM tbluser WHERE username=? AND password=?";
                statement = con.prepareStatement(sql);
                statement.setString(1, username);
                statement.setString(2, password);
                result = statement.executeQuery();
                
                if(result.next()) {
                    role = result.getString("role");
                    
                    if(role.equals("Admin")) {
                        toMainForm.isAdmin(isAdmin);
                    } else {
                        isAdmin = false;
                        toMainForm.isAdmin(isAdmin);  
                    }
                
                    JOptionPane.showMessageDialog(null, "Login successful.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    toMainForm.setVisible(true);
                    this.dispose();
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jlShowOrHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlShowOrHideMouseClicked
        // TODO add your handling code here:
        if(isShown) {
            ImageIcon myImg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("myImg/showPass.png")));
            Image img1 = myImg.getImage();
            Image img2 = img1.getScaledInstance(jlShowOrHide.getWidth(), jlShowOrHide.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon i = new ImageIcon(img2);
            jlShowOrHide.setIcon(i);
            
            jpfPassword.setEchoChar((char) 0);
            jlShowOrHide.setToolTipText("Hide Password");
            isShown = false;
        } else {
            ImageIcon myImg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("myImg/hidePass.png")));
            Image img1 = myImg.getImage();
            Image img2 = img1.getScaledInstance(jlShowOrHide.getWidth(), jlShowOrHide.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon i = new ImageIcon(img2);
            jlShowOrHide.setIcon(i);
            
            jpfPassword.setEchoChar('*');
            jlShowOrHide.setToolTipText("Show Password");
            isShown = true;
        }
    }//GEN-LAST:event_jlShowOrHideMouseClicked

    private void jlShowOrHide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlShowOrHide1MouseClicked
        // TODO add your handling code here:
        if(isShown) {
            ImageIcon myImg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("myImg/showPass.png")));
            Image img1 = myImg.getImage();
            Image img2 = img1.getScaledInstance(jlShowOrHide1.getWidth(), jlShowOrHide1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon i = new ImageIcon(img2);
            jlShowOrHide1.setIcon(i);
            
            jpfPassword1.setEchoChar((char) 0);
            jlShowOrHide1.setToolTipText("Hide Password");
            isShown = false;
        } else {
            ImageIcon myImg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("myImg/hidePass.png")));
            Image img1 = myImg.getImage();
            Image img2 = img1.getScaledInstance(jlShowOrHide1.getWidth(), jlShowOrHide1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon i = new ImageIcon(img2);
            jlShowOrHide1.setIcon(i);
            
            jpfPassword1.setEchoChar('*');
            jlShowOrHide1.setToolTipText("Show Password");
            isShown = true;
        }
    }//GEN-LAST:event_jlShowOrHide1MouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        jtpLoginOrRegister.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginOrRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginOrRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginOrRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginOrRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginOrRegisterForm().setVisible(true);
            }
        });
    }
    
    private void displayIcon() {
        String[] imageNames = {"userIcon.png", "lockIcon.png", "userIcon.png", "lockIcon.png", "hidePass.png", "hidePass.png", "cictLogo.png", "neustLogo.png", "gramLogo.png"};
        JLabel[] labels = {jlUserIcon, jlLockIcon, jlUserIcon1, jlLockIcon1, jlShowOrHide, jlShowOrHide1, jlCictLogo, jlNeustLogo, jlGramLogo};

        for(int i = 0; i < labels.length; i++) {
            ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("myImg/" + imageNames[i])));
            Image img1 = icon.getImage();
            Image img2 = img1.getScaledInstance(labels[i].getWidth(), labels[i].getHeight(), Image.SCALE_SMOOTH);
            ImageIcon i2 = new ImageIcon(img2);
            labels[i].setIcon(i2);
        }
    }
    
    public void setIcon() {
        String imagePath = "myImg/gramLogo.png";
        URL url = getClass().getClassLoader().getResource(imagePath);
        ImageIcon icon = new ImageIcon(url);
        setIconImage(icon.getImage());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jlCictLogo;
    private javax.swing.JLabel jlCreateAccount;
    private javax.swing.JLabel jlGramLogo;
    private javax.swing.JLabel jlLockIcon;
    private javax.swing.JLabel jlLockIcon1;
    private javax.swing.JLabel jlNeustLogo;
    private javax.swing.JLabel jlShowOrHide;
    private javax.swing.JLabel jlShowOrHide1;
    private javax.swing.JLabel jlUserIcon;
    private javax.swing.JLabel jlUserIcon1;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPanel jpRegister;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPasswordField jpfPassword1;
    private javax.swing.JTextField jtfUsername;
    private javax.swing.JTextField jtfUsername1;
    private javax.swing.JTabbedPane jtpLoginOrRegister;
    // End of variables declaration//GEN-END:variables
}
